using System;
using System.Collections.Generic;
using System.Text;

namespace TongFang
{
    public enum Effect : byte
    {
        Static = 1,
        Breathing = 2,
        Wave = 3,
        Reactive = 4,
        Rainbow = 5,
        Ripple = 6,
        Nomo = 8,
        Marquee = 9,
        Raindrop = 10,
        Stack = 12,
        Impact = 13,
        Aurora = 14,
        Neon = 15,
        Spark = 17,
        Flash = 18,
        Mix = 19,
        Music = 34,
        UserMode = 51,
        Unknown = 255
    }

    public enum EffecType : byte
    {
        FW = 0,
        ROW = 1,
        PICTURE = 2,
        MUSIC = 3,
        AP = 4
    }

    public enum Control : byte
    {
        Off = 1,
        Default = 2,
        Welcome = 3
    }

    public enum Layout
    {
        ISO,
        ANSI
    }

    public enum Key : byte
    {
        ESCAPE,
        F1,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        F10,
        F11,
        F12,
        INSERT,
        DELETE,
        HOME,
        END,
        PAGE_UP,
        PAGE_DOWN,

        TILDE,
        ONE,
        TWO,
        THREE,
        FOUR,
        FIVE,
        SIX,
        SEVEN,
        EIGHT,
        NINE,
        ZERO,
        MINUS,
        EQUALS,
        BACKSPACE,
        NUMLOCK,
        NUMPAD_DIVIDE,
        NUMPAD_MULTIPLY,
        NUMPAD_MINUS,

        TAB,
        Q,
        W,
        E,
        R,
        T,
        Y,
        U,
        I,
        O,
        P,
        OPEN_BRACKET,
        CLOSE_BRACKET,
        ANSI_BACKSLASH,
        ENTER,
        NUMPAD_SEVEN,
        NUMPAD_EIGHT,
        NUMPAD_NINE,
        NUMPAD_PLUS,

        CAPS_LOCK,
        A,
        S,
        D,
        F,
        G,
        H,
        J,
        K,
        L,
        SEMICOLON,
        APOSTROPHE,
        ISO_HASH,
        NUMPAD_FOUR,
        NUMPAD_FIVE,
        NUMPAD_SIX,

        LEFT_SHIFT,
        ISO_BACKSLASH,
        Z,
        X,
        C,
        V,
        B,
        N,
        M,
        COMMA,
        PERIOD,
        FORWARD_SLASH,
        RIGHT_SHIFT,
        ARROW_UP,
        NUMPAD_ONE,
        NUMPAD_TWO,
        NUMPAD_THREE,
        NUMPAD_ENTER,

        LEFT_CONTROL,
        LEFT_FN,
        LEFT_WINDOWS,
        LEFT_ALT,
        SPACE,
        RIGHT_ALT,
        MENU,
        RIGHT_CONTROL,
        ARROW_LEFT,
        ARROW_DOWN,
        ARROW_RIGHT,
        NUMPAD_0,
        NUMPAD_PERIOD,
        PRINT_SCREEN,
    }

    public static class Layouts
    {
        public static readonly Dictionary<Key, byte[]> ISO = new Dictionary<Key, byte[]>
        {
            [Key.LEFT_CONTROL] = new byte[] { 105, 106 },
            [Key.LEFT_FN] = new byte[] { 107 },
            [Key.LEFT_WINDOWS] = new byte[] { 108 },
            [Key.LEFT_ALT] = new byte[] { 109 },
            [Key.SPACE] = new byte[] { 110, 111, 112, 113, 114 },
            [Key.RIGHT_ALT] = new byte[] { 115 },
            [Key.MENU] = new byte[] { 116 },
            [Key.RIGHT_CONTROL] = new byte[] { 117 },
            [Key.ARROW_LEFT] = new byte[] { 118 },
            [Key.ARROW_DOWN] = new byte[] { 119 },
            [Key.ARROW_RIGHT] = new byte[] { 120 },
            [Key.NUMPAD_0] = new byte[] { 121 },
            [Key.NUMPAD_PERIOD] = new byte[] { 122 },
            [Key.LEFT_SHIFT] = new byte[] { 84, 85 },
            [Key.ISO_BACKSLASH] = new byte[] { 86 },
            [Key.Z] = new byte[] { 87 },
            [Key.X] = new byte[] { 88 },
            [Key.C] = new byte[] { 89 },
            [Key.V] = new byte[] { 90 },
            [Key.B] = new byte[] { 91 },
            [Key.N] = new byte[] { 92 },
            [Key.M] = new byte[] { 93 },
            [Key.COMMA] = new byte[] { 94 },
            [Key.PERIOD] = new byte[] { 95 },
            [Key.FORWARD_SLASH] = new byte[] { 96 },
            [Key.RIGHT_SHIFT] = new byte[] { 97 },
            [Key.ARROW_UP] = new byte[] { 98 },
            [Key.NUMPAD_ONE] = new byte[] { 99 },
            [Key.NUMPAD_TWO] = new byte[] { 100 },
            [Key.NUMPAD_THREE] = new byte[] { 101 },
            [Key.NUMPAD_ENTER] = new byte[] { 102 },
            [Key.CAPS_LOCK] = new byte[] { 63 },
            [Key.A] = new byte[] { 65 },
            [Key.S] = new byte[] { 66 },
            [Key.D] = new byte[] { 67 },
            [Key.F] = new byte[] { 68 },
            [Key.G] = new byte[] { 69 },
            [Key.H] = new byte[] { 70 },
            [Key.J] = new byte[] { 71 },
            [Key.K] = new byte[] { 72 },
            [Key.L] = new byte[] { 73 },
            [Key.SEMICOLON] = new byte[] { 74 },
            [Key.APOSTROPHE] = new byte[] { 75 },
            [Key.ISO_HASH] = new byte[] { 76 },
            [Key.NUMPAD_FOUR] = new byte[] { 78 },
            [Key.NUMPAD_FIVE] = new byte[] { 79 },
            [Key.NUMPAD_SIX] = new byte[] { 80 },
            [Key.TAB] = new byte[] { 42 },
            [Key.Q] = new byte[] { 44 },
            [Key.W] = new byte[] { 45 },
            [Key.E] = new byte[] { 46 },
            [Key.R] = new byte[] { 47 },
            [Key.T] = new byte[] { 48 },
            [Key.Y] = new byte[] { 49 },
            [Key.U] = new byte[] { 50 },
            [Key.I] = new byte[] { 51 },
            [Key.O] = new byte[] { 52 },
            [Key.P] = new byte[] { 53 },
            [Key.OPEN_BRACKET] = new byte[] { 54 },
            [Key.CLOSE_BRACKET] = new byte[] { 55 },
            [Key.ENTER] = new byte[] { 56 },
            [Key.NUMPAD_SEVEN] = new byte[] { 57 },
            [Key.NUMPAD_EIGHT] = new byte[] { 58 },
            [Key.NUMPAD_NINE] = new byte[] { 59 },
            [Key.NUMPAD_PLUS] = new byte[] { 60 },
            [Key.TILDE] = new byte[] { 21 },
            [Key.ONE] = new byte[] { 22 },
            [Key.TWO] = new byte[] { 23 },
            [Key.THREE] = new byte[] { 24 },
            [Key.FOUR] = new byte[] { 25 },
            [Key.FIVE] = new byte[] { 26 },
            [Key.SIX] = new byte[] { 27 },
            [Key.SEVEN] = new byte[] { 28 },
            [Key.EIGHT] = new byte[] { 29 },
            [Key.NINE] = new byte[] { 30 },
            [Key.ZERO] = new byte[] { 31 },
            [Key.MINUS] = new byte[] { 32 },
            [Key.EQUALS] = new byte[] { 33 },
            [Key.BACKSPACE] = new byte[] { 35 },
            [Key.NUMLOCK] = new byte[] { 36 },
            [Key.NUMPAD_DIVIDE] = new byte[] { 37 },
            [Key.NUMPAD_MULTIPLY] = new byte[] { 38 },
            [Key.NUMPAD_MINUS] = new byte[] { 39 },
            [Key.ESCAPE] = new byte[] { 0 },
            [Key.F1] = new byte[] { 1 },
            [Key.F2] = new byte[] { 2 },
            [Key.F3] = new byte[] { 3 },
            [Key.F4] = new byte[] { 4 },
            [Key.F5] = new byte[] { 5 },
            [Key.F6] = new byte[] { 6 },
            [Key.F7] = new byte[] { 7 },
            [Key.F8] = new byte[] { 8 },
            [Key.F9] = new byte[] { 9 },
            [Key.F10] = new byte[] { 10 },
            [Key.F11] = new byte[] { 11 },
            [Key.F12] = new byte[] { 12 },
            [Key.INSERT] = new byte[] { 13 },
            [Key.DELETE] = new byte[] { 14 },
            [Key.HOME] = new byte[] { 15 },
            [Key.END] = new byte[] { 16 },
            [Key.PAGE_UP] = new byte[] { 17 },
            [Key.PAGE_DOWN] = new byte[] { 18 }
        };

        public static readonly Dictionary<Key, byte[]> ANSI = new Dictionary<Key, byte[]>
        {
            [Key.LEFT_CONTROL] = new byte[] { 105 },
            [Key.LEFT_FN] = new byte[] { 107 },
            [Key.LEFT_WINDOWS] = new byte[] { 108 },
            [Key.LEFT_ALT] = new byte[] { 109 },
            [Key.SPACE] = new byte[] { 112 },
            [Key.RIGHT_ALT] = new byte[] { 115 },
            [Key.MENU] = new byte[] { 116 },
            [Key.RIGHT_CONTROL] = new byte[] { 117 },
            [Key.ARROW_LEFT] = new byte[] { 118 },
            [Key.ARROW_DOWN] = new byte[] { 119 },
            [Key.ARROW_RIGHT] = new byte[] { 120 },
            [Key.LEFT_SHIFT] = new byte[] { 85 },
            [Key.Z] = new byte[] { 87 },
            [Key.X] = new byte[] { 88 },
            [Key.C] = new byte[] { 89 },
            [Key.V] = new byte[] { 90 },
            [Key.B] = new byte[] { 91 },
            [Key.N] = new byte[] { 92 },
            [Key.M] = new byte[] { 93 },
            [Key.COMMA] = new byte[] { 94 },
            [Key.PERIOD] = new byte[] { 95 },
            [Key.FORWARD_SLASH] = new byte[] { 96 },
            [Key.RIGHT_SHIFT] = new byte[] { 97 },
            [Key.ARROW_UP] = new byte[] { 98 },
            [Key.END] = new byte[] { 99 },
            [Key.CAPS_LOCK] = new byte[] { 63 },
            [Key.A] = new byte[] { 65 },
            [Key.S] = new byte[] { 66 },
            [Key.D] = new byte[] { 67 },
            [Key.F] = new byte[] { 68 },
            [Key.G] = new byte[] { 69 },
            [Key.H] = new byte[] { 70 },
            [Key.J] = new byte[] { 71 },
            [Key.K] = new byte[] { 72 },
            [Key.L] = new byte[] { 73 },
            [Key.SEMICOLON] = new byte[] { 74 },
            [Key.APOSTROPHE] = new byte[] { 75 },
            [Key.ENTER] = new byte[] { 77 },
            [Key.PAGE_DOWN] = new byte[] { 78 },
            [Key.TAB] = new byte[] { 42 },
            [Key.Q] = new byte[] { 44 },
            [Key.W] = new byte[] { 45 },
            [Key.E] = new byte[] { 46 },
            [Key.R] = new byte[] { 47 },
            [Key.T] = new byte[] { 48 },
            [Key.Y] = new byte[] { 49 },
            [Key.U] = new byte[] { 50 },
            [Key.I] = new byte[] { 51 },
            [Key.O] = new byte[] { 52 },
            [Key.P] = new byte[] { 53 },
            [Key.OPEN_BRACKET] = new byte[] { 54 },
            [Key.CLOSE_BRACKET] = new byte[] { 55 },
            [Key.BACKSLASH] = new byte[] { 56 },
            [Key.PAGE_UP] = new byte[] { 57 },
            [Key.TILDE] = new byte[] { 21 },
            [Key.ONE] = new byte[] { 22 },
            [Key.TWO] = new byte[] { 23 },
            [Key.THREE] = new byte[] { 24 },
            [Key.FOUR] = new byte[] { 25 },
            [Key.FIVE] = new byte[] { 26 },
            [Key.SIX] = new byte[] { 27 },
            [Key.SEVEN] = new byte[] { 28 },
            [Key.EIGHT] = new byte[] { 29 },
            [Key.NINE] = new byte[] { 30 },
            [Key.ZERO] = new byte[] { 31 },
            [Key.MINUS] = new byte[] { 32 },
            [Key.EQUALS] = new byte[] { 33 },
            [Key.BACKSPACE] = new byte[] { 35 },
            [Key.HOME] = new byte[] { 36 },
            [Key.ESCAPE] = new byte[] { 0 },
            [Key.F1] = new byte[] { 1 },
            [Key.F2] = new byte[] { 2 },
            [Key.F3] = new byte[] { 3 },
            [Key.F4] = new byte[] { 4 },
            [Key.F5] = new byte[] { 5 },
            [Key.F6] = new byte[] { 6 },
            [Key.F7] = new byte[] { 7 },
            [Key.F8] = new byte[] { 8 },
            [Key.F9] = new byte[] { 9 },
            [Key.F10] = new byte[] { 10 },
            [Key.F11] = new byte[] { 11 },
            [Key.F12] = new byte[] { 12 },
            [Key.INSERT] = new byte[] { 13 },
            [Key.PRINT_SCREEN] = new byte[] { 14 },
            [Key.DELETE] = new byte[] { 15 }
        };
    };
}
